/*
* generated by Xtext
*/
package org.xtext.example.iptables.ui.contentassist;

import org.xtext.example.iptables.ui.contentassist.AbstractIptablesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class IptablesProposalProvider extends AbstractIptablesProposalProvider {

}
