/*
 * generated by Xtext
 */
package org.xtext.example.iptables;

import org.eclipse.xtext.linking.ILinker;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IptablesRuntimeModule extends org.xtext.example.iptables.AbstractIptablesRuntimeModule {
	@Override
	public Class<? extends ILinker> bindILinker(){
		return IptablesLinker.class;
	}
}
