/*
* generated by Xtext
*/
package org.xtext.example.iptables.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.iptables.services.IptablesGrammarAccess;

public class IptablesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IptablesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.iptables.parser.antlr.internal.InternalIptablesParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.iptables.parser.antlr.internal.InternalIptablesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public IptablesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IptablesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
