/*
 * generated by Xtext
 */
package org.xtext.example.iptables.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IptablesUiModule extends org.xtext.example.iptables.ui.AbstractIptablesUiModule {
	public IptablesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
